_BASE_: "base_att_video_caption.yaml"

OUTPUT_DIR: "snapshots/salstm_baseline"

MODEL: 
  WEIGHTS: "/media/winne/DATA2/new_code/msvd_datasets/salstm_baseline_model.pth"

  SALSTM:
    ATT_EMBED_SIZE: 256
    CTX_DROPOUT: 0.5
    ATT_EMBED_DROPOUT: 0.0
    LM_DROPOUT: 0.5
  

