_BASE_: "../mm_understanding_base.yaml"

####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'Flickr30kDataset'
  VAL: 'Flickr30kDataset'
  TEST: 'Flickr30kDataset'

######################################### Engine #########################################
ENGINE:
  NAME: 'RetrievalTrainer'

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 128
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
  FEATS_FOLDER: '../open_source_dataset/flickr30k/features/up_down'
  ANNO_FOLDER: '../open_source_dataset/flickr30k'
  SEQ_PER_SAMPLE:  1
  MAX_FEAT_NUM: 51

######################################### MODEL #########################################
MODEL:
  MAX_SEQ_LEN: 30
  META_ARCHITECTURE: 'TDENRetrieval'
  ENCODER: 'TwoStreamBertEncoder'
  DECODER: ''
  PREDICTOR: 'MultiModalSimilarity'
  WEIGHTS: '../pretrain/TDEN/TDEN.pth'

######################################### BERT #########################################
  BERT:
    HIDDEN_SIZE: 768
    HIDDEN_DROPOUT_PROB: 0.2
    HIDDEN_ACT: "gelu"
    NUM_ATTENTION_HEADS: 12
    INTERMEDIATE_SIZE: 3072
    INTERMEDIATE_DROP: 0.2
    FFN_DROPOUT_PROB: 0.2
    ATTENTION_PROBS_DROPOUT_PROB: 0.1
    NUM_HIDDEN_LAYERS: 12
    V_NUM_HIDDEN_LAYERS: 6
    NUM_UNDERSTANDING_LAYERS: 0
    NUM_GENERATION_LAYERS: 0

    LAYER_DROP: 0.1
    V_LAYER_DROP: 0.1

######################################### MM_PREDICTOR #########################################
  MM_PREDICTOR:
    POOLER_INPUT_SIZE: 768
    POOLER_OUTPUT_SIZE: 1024
    POOLER_BN: True
    POOLER_DROPOUT: 0.1

#################################### Token embedding ####################################
  TOKEN_EMBED:
    NAME: 'TokenBaseEmbedding'
    DIM: 768
    ACTIVATION: 'none'
    USE_NORM: True
    DROPOUT: 0.2
    POSITION: 'NNEmbeddingEncoding'
    POSITION_MAX_LEN: 512
    TYPE_VOCAB_SIZE: 3

#################################### Visual embedding ####################################
  VISUAL_EMBED:
    NAME: 'VisualBaseEmbedding'
    IN_DIM: 2048
    OUT_DIM: 768
    LOCATION_SIZE: 5
    ACTIVATION: 'none'
    USE_NORM: True
    DROPOUT: 0.2

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 100
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 2
  BASE_LR: 0.00002
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.999]
  EPS: 1e-8
  GRAD_CLIP: 2.0
  GRAD_CLIP_TYPE: 'norm'
  NORM_TYPE: 2.0
  WRITE_PERIOD: 20
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'WarmupMultiStepLR'
  STEPS: [30, 60]
  GAMMA: 0.1
  WARMUP: 10

####################################### losses ####################################### 
LOSSES:
  NAMES: ['BatchTriplet']
  MARGIN: 0.2
  MAX_VIOLATION: True

INFERENCE:
  VOCAB: ''
  ID_KEY: 'image_id'
  VALUE: 'caption'
  NAME: 'RetrievalEvaler'
  VAL_ANNFILE: '../open_source_dataset/flickr30k/all_data_final_val_set0_2014.jsonline'
  TEST_ANNFILE: '../open_source_dataset/flickr30k/all_data_final_test_set0_2014.jsonline'
  GENERATION_MODE: False
