_BASE_: "meshed_memory.yaml"

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 16

######################################### Engine #########################################
ENGINE:
  NAME: 'RLTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '../meshed_memory_xe.pth'

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 50
  BASE_LR: 0.000005

####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'FixLR'