_BASE_: "tden.yaml"

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 24

######################################### Engine #########################################
ENGINE:
  NAME: 'RLTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '{path_to_tden_capton_xe_model}'

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 50
  BASE_LR: 0.000005

####################################### scorer ####################################### 
SCORER:
  NAME: 'BertTokenizedScorer'
  TYPES: ['Cider']
  WEIGHTS: [1.0]
  GT_PATH: '../open_source_dataset/mscoco_dataset/coco_pretrain_train_gts.pkl'
  CIDER_CACHED: '../open_source_dataset/mscoco_dataset/coco_pretrain_train_cider.pkl'

####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'StepLR'
  STEP_SIZE: 18
  GAMMA: 0.8