####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'MSCoCoBertDataset'
  VAL: 'MSCoCoBertDataset'
  TEST: 'MSCoCoBertDataset'

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 4
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
  FEATS_FOLDER: '../open_source_dataset/mscoco_dataset/features/up_down_with_bbox'
  ANNO_FOLDER:  '../open_source_dataset/mscoco_dataset'
  SEQ_PER_SAMPLE:  5
  MAX_FEAT_NUM: 51

######################################### Engine #########################################
ENGINE:
  NAME: 'DefaultTrainer'

######################################### MODEL #########################################
MODEL:
  VOCAB_SIZE: 30522 # include <BOS>/<EOS>
  META_ARCHITECTURE: 'TDENCaptioner'
  ENCODER: 'TwoStreamBertEncoder'
  DECODER: 'DecoupleBertDecoder'
  PREDICTOR: 'BertPredictionHead'
  MAX_SEQ_LEN: 20
  WEIGHTS: '{path_to_tden_pretrain_model}'

######################################### BERT #########################################
  BERT:
    HIDDEN_SIZE: 768
    HIDDEN_DROPOUT_PROB: 0.1
    HIDDEN_ACT: "gelu"
    NUM_ATTENTION_HEADS: 12
    INTERMEDIATE_SIZE: 3072
    INTERMEDIATE_DROP: 0.1
    FFN_DROPOUT_PROB: 0.1
    ATTENTION_PROBS_DROPOUT_PROB: 0.1
    NUM_HIDDEN_LAYERS: 12
    V_NUM_HIDDEN_LAYERS: 6
    NUM_UNDERSTANDING_LAYERS: 0
    NUM_GENERATION_LAYERS: 6

#################################### Token embedding ####################################
  TOKEN_EMBED:
    NAME: 'TokenBaseEmbedding'
    DIM: 768
    ACTIVATION: 'none'
    USE_NORM: True
    DROPOUT: 0.1
    POSITION: 'NNEmbeddingEncoding'
    POSITION_MAX_LEN: 512
    TYPE_VOCAB_SIZE: 3

#################################### Visual embedding ####################################
  VISUAL_EMBED:
    NAME: 'VisualBaseEmbedding'
    IN_DIM: 2048
    OUT_DIM: 768
    LOCATION_SIZE: 5
    ACTIVATION: 'none'
    USE_NORM: True
    DROPOUT: 0.1
    
####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 10
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  BASE_LR: 0.00003
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.0
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.999]
  EPS: 1e-8
  GRAD_CLIP: 0.1
  GRAD_CLIP_TYPE: 'value'
  NORM_TYPE: 2.0
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'WarmupLinearSchedule'
  WARMUP: 2 # EPOCH(10) * WARMUP_PROPORTION(0.2) = 2

####################################### losses ####################################### 
LOSSES:
  NAMES: ['LabelSmoothing']
  LABELSMOOTHING: 0.1

####################################### decode strategy ####################################### 
DECODE_STRATEGY:
  NAME: 'BeamSearcher'
  BEAM_SIZE: 2

####################################### evaluation ####################################### 
INFERENCE:
  NAME: 'COCOEvaler'
  VOCAB: 'BERT'
  ID_KEY: 'image_id'
  VALUE: 'caption'
  VAL_ANNFILE: '../open_source_dataset/mscoco_dataset/captions_val5k.json'
  TEST_ANNFILE: '../open_source_dataset/mscoco_dataset/captions_test5k.json'
  GENERATION_MODE: True
