_BASE_: "transformer.yaml"

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 16

######################################### Engine #########################################
ENGINE:
  NAME: 'RLTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '{path_to_xe_model}'

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 30
  BASE_LR: 0.00001

####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'FixLR'