_BASE_: "base_att_image_caption.yaml"

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 16
  TEST_BATCH_SIZE: 32

######################################### Engine #########################################
ENGINE:
  NAME: 'RLTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '{path_to_xe_model}'
  UPDOWN:
    ATT_EMBED_SIZE: 512
    DROPOUT1: 0.0
    DROPOUT2: 0.0
    ATT_EMBED_DROPOUT: 0.0

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 30
  BASE_LR: 0.00001
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'FixLR'