_BASE_: "base_att_image_caption.yaml"

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 5 # 5 x 4gpu = 20
  NUM_WORKERS: 4

######################################### Engine #########################################
ENGINE:
  NAME: 'RLTrainer'

######################################### Scheduled sampling #########################################
SCHEDULED_SAMPLING:
  START_EPOCH: 6
  INC_EVERY_EPOCH: 5
  INC_PROB: 0.05
  MAX_PROB: 0.5

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '{path_to_xe_model}'
  ENCODER: 'LowRankBilinearEncoder'
  DECODER: 'XLANDecoder'

####################################### BILINEAR LAN ############################################
  BILINEAR:
    DIM: 1024
    HEAD: 8
    BIFEAT_EMB_ACT: 'relu'
    ACT: 'celu'
    ELU_ALPHA: 1.3
    ENCODE:
      ATT_MID_DIM: [128, 64, 128]
      ATT_MID_DROPOUT: 0.1
      DROPOUT: 0.5
      BIFEAT_EMB_DROPOUT: 0.3
      LAYERS: 4
    DECODE:
      ATT_MID_DIM: [128, 64, 128]
      ATT_MID_DROPOUT: 0.1
      DROPOUT: 0.5
      LAYERS: 1

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 35
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  BASE_LR: 0.00001
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.999]
  EPS: 1.0e-8
  GRAD_CLIP: 0.1
  GRAD_CLIP_TYPE: 'value'
  NORM_TYPE: 2.0
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'StepLR'
  STEP_SIZE: 10
  GAMMA: 0.8