####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'MSCoCoDatasetMapper'
  TEST: 'MSCoCoDatasetMapper'

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 1
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 0
  FEATS_FOLDER: '/export/dataset/mscoco_torch/feature/up_down_100'
  ANNO_FILE:  '/export/dataset/mscoco_open_source/mscoco_caption_anno'
  SEQ_PER_IMG:  5
  MAX_FEAT_NUM: 50

######################################### MODEL #########################################
MODEL:
  VOCAB_SIZE: 9488 # include <BOS>/<EOS>
  META_ARCHITECTURE: 'RnnAttEncoderDecoder'
  ENCODER: 'UpDownEncoder'
  ENCODER_DIM: 1024
  DECODER: 'UpDownDecoder'
  DECODER_DIM: 1024
  PREDICTOR: 'BasicPredictor'
  MAX_SEQ_LEN: 17

#################################### Token embedding ####################################
  TOKEN_EMBED:
    NAME: 'TokenBasicEmbedding'
    DIM: 1024
    ACTIVATION: 'relu'
    USE_NORM: False
    DROPOUT: 0.5

#################################### Visual embedding ####################################
  VISUAL_EMBED:
    NAME: 'VisualBasicEmbedding'
    IN_DIM: 2048
    OUT_DIM: 1024
    ACTIVATION: 'relu'
    USE_NORM: False
    DROPOUT: 0.5
  
####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 10
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  BASE_LR: 0.0005
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.0
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.999]
  EPS: 1e-8
  GRAD_CLIP: 0.1
  GRAD_CLIP_TYPE: 'value'
  NORM_TYPE: 2.0
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'StepLR'
  STEP_SIZE: 3
  GAMMA: 0.1

####################################### losses ####################################### 
LOSSES:
  NAME: 'CrossEntropy'

####################################### evaluation ####################################### 
INFERENCE:
  NAME: 'COCOEvaler'
  VOCAB: '/export/dataset/mscoco_open_source/coco_vocabulary.txt'
  ID_KEY: 'image_id'
  CAP_KEY: 'caption'
  VAL_ANNFILE: '/export/dataset/mscoco_open_source/captions_val5k.json'
  TEST_ANNFILE: '/export/dataset/mscoco_open_source/captions_test5k.json'
  BEAM_SIZE: 1

